# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a17f5e5c239f1d6767e48f2db4a79d414bb0abb415bcaffb31ae202ad905aa6b8e41f2a91b4093c0d018908cd8e7e7a035cb216e68419860fe0ce2dc28fedb59

test:
  secret_key_base: aedb46f87067ce1778ac0535a7cce32f9bac4da0de4de74634ffa1ff43c61f8d0e8156d7417b180221fe41fdc45551b9aba723c55aac0c0f6267ddf1d4f4e77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
